### ISSUE TITLE
Problem with unescaped slash in character set in regex

### ISSUE THREAD

**Issue by faf** [bleargh45/JavaScript-Minifier-XS#6]
In JS it is possible to include unescaped slash in a character set. So this code is valid:

```
var a = ""; var re = /[/"]/i; console.log(re.test(a));
```

However, if one would try to minify that code, the minifier will crash with : ```unterminated quoted string literal``` error.

The more complicated real life example could be found here: https://github.com/zoffixznet/JavaScript-Minifier/issues/8#issuecomment-772004250

**Comment by bleargh45** [comment]
Appreciate the example.  Will try to get to this later in the week.

**Comment by bleargh45** [comment]
Have a fix for this locally, which will go out in the next release.

Appreciate the pointed and detailed description of the scenario that causes this; made it **much** easier to correct.

**Comment by bleargh45** [comment]
Should be fixed by cc9f37935, released in v0.14
