### ISSUE TITLE
v0.14 depends on Test::DiagINC

### ISSUE THREAD

**Issue by stigtsp** [bleargh45/JavaScript-Minifier-XS#7]
Hi there :)

While upgrading JavaScript::Minifier::XS in nixpkgs from v0.13 -> v0.14 I noticed that the tarball from CPAN has Test::DiagINC as a hard dependency for tests, although this is not in the cpanfile. 

``
t/00-report-prereqs.t .. Can't locate Test/DiagINC.pm in @INC (you may need to install the Test::DiagINC module) (@INC contains: ...
``

**Comment by bleargh45** [comment]
That dependency on `Test::DiagINC` is present in `Makefile.PL` as well as in the `META.*` files (and which is unchanged from the previous v0.13 release).

Would you mind sharing how you are building/installing `JavaScript::Minifier::XS`, so I can get a better idea of how your system did not pull in the expected dependencies?

**Comment by stigtsp** [comment]
Woops! My apologies. A typo propagated into my system here, mistaking v0.11 for v0.13. Sorry for the disturbance. You're quite right. I've bundled `Test::DiagINC` with the upgrade from v0.11 -> v0.14 in nixpkgs.

**Comment by bleargh45** [comment]
Ah, gotcha.  Yes... when switching to using `Dist::Zilla` for doing release management, `Test::DiagINC` was added as a test dependency.

However, if you are using `cpan`, `cpanm`, or `cpm` to do the install then those dependencies should be getting installed properly for you.

Happy to continue to try to help diagnose build/install problems, if you care to provide more info about how your build/install is being done.

**Comment by stigtsp** [comment]
Thanks :) I'm packaging Perl modules for the [nixpkgs](https://github.com/nixos/nixpkgs) repository, and was doing an update of JavaScript::Minifier::XS. It's a declarative way of defining environments, worth checking out.
